baseURL = "https://seabornlee.cn/"
languageCode = "zh-cn"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "文章"
  URL = "https://life.seabornlee.cn"
  weight = 2

  [[menu.header]]
  name = "视频"
  URL = "https://space.bilibili.com/21815801/video"
  weight = 3

  [[menu.header]]
  name = "时间线"
  URL = "https://timeline.seabornlee.cn/timeline"
  weight = 4

  [[menu.footer]]
  name = "文章"
  URL = "https://life.seabornlee.cn"
  weight = 2

  [[menu.footer]]
  name = "视频"
  URL = "https://space.bilibili.com/21815801/video"
  weight = 3

  [[menu.footer]]
  name = "时间线"
  URL = "https://timeline.seabornlee.cn/timeline"
  weight = 4

[params]

  sections = ["showcase", "about", "experience", "client-and-work", "testimonial", "education", "certification", "contact", "newsletter"]

  googleTagManagerID = "G-TPHYCP133Q" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Seaborn"
    text2 = "Lee"

  [params.footer]
      copyright = "© Seaborn. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
